---

- name: Stop all cluster components
  hosts: all
  remote_user: root

  tasks:
    - name: Stop brokers
      ansible.builtin.systemd_service:
        state: started
        name: broker.service
        deamon_reload: true
    - name: Stop bookie cluster
      ansible.builtin.systemd_service:
        state: started
        name: bookkeeper.service
        deamon_reload: true
    - name: Stop zookeeper cluster
      ansible.builtin.systemd_service:
        state: started
        name: zookeeper.service
        daemon_reload: true
