---

- name: Install and configure ZooKeeper on nodes
  hosts: all
  remote_user: root

  tasks:
    - name: Ensure default-jre is installed
      ansible.builtin.apt:
        name: default-jre
        state: latest
    - name: Ensure zookeeper user exists
      ansible.builtin.user:
        name: zookeeper
        shell: /bin/bash
        state: present
    - name: Download and untar ZooKeeper
      ansible.builtin.unarchive:
        src: https://dlcdn.apache.org/zookeeper/zookeeper-{{ zookeeper.version }}/apache-zookeeper-{{ ansible_env.zookeeper.version }}-bin.tar.gz
        dest: /opt/{{ zookeeper.extracted_filename }}
        owner: zookeeper
        group: zookeeper
        remote_src: yes
    - name: Configure ZooKeeper
      ansible.builtin.template:
        src: templates/zoo.cfg.j2
        dst: /opt/{{ zookeeper.extracted_filename }}/conf/zoo.conf
        owner: zookeeper
        group: zookeeper
        force: yes
    - name: Install ZooKeeper Systemd Service
      ansible.builtin.template:
        src: templates/zookeeper.service.j2
        dst: /etc/systemd/system/zookeeper.service
        owner: root
        group: root
    - name: Initialize zookeeper
      copy:
        dest: /var/zookeeper/myid
        content: |
          {{ zookeeper_node_id }}
    - name: Start zookeeper
      ansible.builtin.systemd_service:
        state: started
        daemon_reload: true
        name: zookeeper
